fix: updates in workflow files (#16)
* fix: fixed umbrella chart

* fix: updates on various workflow files

diff --git a/.github/workflows/plugins-umbrella-chart-release-tag.yaml b/.github/workflows/plugins-umbrella-chart-release-tag.yaml
--- a/.github/workflows/plugins-umbrella-chart-release-tag.yaml
+++ b/.github/workflows/plugins-umbrella-chart-release-tag.yaml
@@ -54,22 +54,36 @@ jobs:
           helm repo update
 
           echo "Fetching latest versions for dependencies..."
-          COLLABORATOR_VERSION=$(helm search repo ${HELM_REPO_NAME}/collaborator-plugin -o json | jq -r '.[0].version')
-          TEAMREPO_VERSION=$(helm search repo ${HELM_REPO_NAME}/teamrepo-plugin -o json | jq -r '.[0].version')
+          COLLABORATOR_PLUGIN_VERSION=$(helm search repo ${HELM_REPO_NAME}/github-provider-kog-collaborator-plugin -o json | jq -r '.[0].version')
+          TEAMREPO_PLUGIN_VERSION=$(helm search repo ${HELM_REPO_NAME}/github-provider-kog-teamrepo-plugin -o json | jq -r '.[0].version')
 
-          if [ -z "$COLLABORATOR_VERSION" ] || [ -z "$TEAMREPO_VERSION" ]; then
-            echo "Error: Could not determine latest version for one or more plugin charts."
+          if [ -z "$COLLABORATOR_PLUGIN_VERSION" ]; then
+            echo "Error: Could not determine latest version of github-provider-kog-collaborator-plugin" >&2
             exit 1
+          else
+            echo "Latest github-provider-kog-collaborator-plugin version: $COLLABORATOR_PLUGIN_VERSION"
+          fi
+
+          if [ -z "$TEAMREPO_PLUGIN_VERSION" ]; then
+            echo "Error: Could not determine latest version of github-provider-kog-teamrepo-plugin" >&2
+            exit 1
+          else
+            echo "Latest github-provider-kog-teamrepo-plugin version: $TEAMREPO_PLUGIN_VERSION"
           fi
           
           echo "Updating umbrella chart to version ${UMBRELLA_VERSION} in-memory..."
           
           yq e ".version = \"${UMBRELLA_VERSION}\"" -i "${CHART_DIR}/Chart.yaml"
-          yq e "(.dependencies[] | select(.name == \"collaborator-plugin\")).version = \"${COLLABORATOR_VERSION}\"" -i "${CHART_DIR}/Chart.yaml"
-          yq e "(.dependencies[] | select(.name == \"teamrepo-plugin\")).version = \"${TEAMREPO_VERSION}\"" -i "${CHART_DIR}/Chart.yaml"
+          yq e "(.dependencies[] | select(.name == \"github-provider-kog-collaborator-plugin\")).version = \"${COLLABORATOR_PLUGIN_VERSION}\"" -i "${CHART_DIR}/Chart.yaml"
+          yq e "(.dependencies[] | select(.name == \"github-provider-kog-teamrepo-plugin\")).version = \"${TEAMREPO_PLUGIN_VERSION}\"" -i "${CHART_DIR}/Chart.yaml"
 
           echo "Final Chart.yaml content for this release:"
           cat "${CHART_DIR}/Chart.yaml"
+      
+      - name: Helm lint
+        run: |
+          CHART_DIR="./github-provider-kog-plugins-chart"
+          helm lint "${CHART_DIR}"
 
       - name: Publish Helm chart
         uses: stefanprodan/helm-gh-pages@master
